#!/usr/bin/python
import sys
import datetime

template = """---
title: "Task {date}"
author: [english]
keyword: [productive]
---
# Ielts prompts\\

# Story with New Vocabulary\\

# Vocabulary review\\
Here’s a list of the ‘less common’ collocations and phrases yesterday:
* word

<!-- This mainly focusing on your writing so you don't have to turning notebook's paper. Type everything from the notebook then reparaphrase back in the notebook, include language, grammar and vocabulary study -->
"""

# adding path to date
#date = (datetime.date.today() if len(sys.argv) < 2
        # Expecting filename in YYYY-MM-DD.foo format
#        else sys.argv[1].rsplit(".", 1)[0])

#remove path on date
date = (datetime.date.today() if len(sys.argv) < 2
else sys.argv[1].rsplit(".", 1)[0].rsplit("/", 1)[1])
print(template.format(date=date))
