#!/usr/bin/python
import sys
import datetime

template = """# {date}
---
title: "Gatsby is awesome"
date: "2019-01-02"
image: ../images/howl650.jpg
featured: true
tags:
- one
- two
---
## Review Vocabulary
* [ ]
* [ ]

## New Vocabulary
* [ ]
* [ ]"""


date = (datetime.date.today() if len(sys.argv) < 2
        # Expecting filename in YYYY-MM-DD.foo format
        else sys.argv[1].rsplit(".", 1)[0])
print(template.format(date=date))
