#!/usr/bin/python
import sys
import datetime

template = """---
title: "Markdown"
author: [uliah]
date: "{date}"
keywords: [English, TBI]
---
# Sub title \\

Write here..\\

## Vocabulary review\\
Here is a list of less common or new collacations, phrases, or word in the essay above:
*

"""

# adding path to date
#date = (datetime.date.today() if len(sys.argv) < 2
        # Expecting filename in YYYY-MM-DD.foo format
#        else sys.argv[1].rsplit(".", 1)[0])

#remove path on date
date = (datetime.date.today() if len(sys.argv) < 2
else sys.argv[1].rsplit(".", 1)[0].rsplit("/", 1)[1])
print(template.format(date=date))
